Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReliableCabs.edmx;
using ReliableCabs.Models;
using System.Web.Security;
using System.Text.RegularExpressions;

namespace ReliableCabs.Controllers
{
    public class DriverController : Controller
    {
        //ReliableCabs.edmx.OnlineAssetMgmtEntities Assets = new ReliableCabs.edmx.OnlineAssetMgmtEntities();
        ReliableCabs.edmx.ReliablecabsEntities Assets = new ReliableCabs.edmx.ReliablecabsEntities();

        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                ReliableCabs.Models.ClientModel clientmodel = new ReliableCabs.Models.ClientModel();

              
                clientmodel.ListFundsDetails = Assets.GetCashFundDetails().ToList();
                if (clientmodel.ListFundsDetails.Count > 0)
                {
                    ViewBag.NetAmount = clientmodel.ListFundsDetails.FirstOrDefault().NetAmount;
                }
                else
                {
                    ViewBag.NetAmount = 0.00;
                }

                //clientmodel.ListClients = Assets.Clients.ToList();
                //clientmodel.ListSubscription = Assets.Subscriptions.ToList();
                //List<Status> Status = Assets.Status.ToList();
                //ViewBag.StatusList = new SelectList(Status, "StatusId", "Status1");


                List<Client> clients = Assets.Clients.ToList();
                List<Subscription> subscriptions = Assets.Subscriptions.ToList();
                List<Status> status = Assets.Status.ToList();

                var clientmodel1 = from e in clients
                                     join d in subscriptions on e.ClientId equals d.ClientId 
                                    join i in status on d.StatusId equals i.StatusId
                                   select new ViewModel
                                   {
                                       client = e,
                                       subscription = d,
                                       status = i
                                   };  




                return View(clientmodel1);
               
            }
            else
            {
                return RedirectToAction("Index", "Login");
          
            }
        }

      
        public ActionResult Index1(int id)
        {
              ReliableCabs.Models.ClientModel clientmodel = new ReliableCabs.Models.ClientModel();

                clientmodel.ListClients = Assets.Clients.Where(x=>x.ClientId == id).ToList();
                clientmodel.ListFundsDetails = Assets.GetCashFundDetails().ToList();
                return PartialView("PartialDriverIndex", clientmodel);
              
        }

        public JsonResult MobileCheckAvailability(string userdata)
        {
            System.Threading.Thread.Sleep(150);
            var searchdata = Assets.Clients.Where(x => x.Mobile == userdata).FirstOrDefault();
            if (searchdata != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        public JsonResult NameCheckAvailability(string userdata)
        {
            System.Threading.Thread.Sleep(150);
            var searchdata = Assets.Clients.Where(x => x.FirstName == userdata).FirstOrDefault();
            if (searchdata != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }


        public JsonResult EmailCheckAvailability(string userdata)
        {
            System.Threading.Thread.Sleep(150);
            using (ReliablecabsEntities db = new ReliablecabsEntities())
            {
                var searchdata = db.Clients.Where(x => x.Email == userdata).FirstOrDefault();
                if (searchdata != null)
                {
                     string emailRegex = @"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(userdata))
                    {
                        ModelState.AddModelError("Email", "Please Enter Correct Email Address");
                        return Json(2);
                    }
                    else
                    {
                        return Json(1);
                    }
                }
                else
                {
                    string emailRegex = @"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$";
                    Regex re = new Regex(emailRegex);
                    if (!re.IsMatch(userdata))
                    {
                        ModelState.AddModelError("Email", "Please Enter Correct Email Address");
                        return Json(2);
                    }
                    else
                    {

                        return Json(0);
                    }
                }
            }
        }

        [HttpPost]
        public ActionResult InsertClient(Client customer)
        {

          //  Assets.AddClientDetails(customer.FirstName, customer.LastName, customer.Mobile, customer.Email, customer.DriverLicenceNo, customer.PhysicalAddress, customer.OtherInfo);


            return Json(true);

        }


        public ActionResult InsertDriverDetails()
        {
            ReliableCabs.Models.ClientModel client = new ReliableCabs.Models.ClientModel();
            client.ListClients = Assets.Clients.ToList();

            return View();
        }

        public ActionResult InsertDriverDetail(ClientModel client)
        {
            ReliableCabs.Models.ClientModel clients = new ReliableCabs.Models.ClientModel();
            Assets.AddClientDetails(client.FirstName, client.LastName, client.Mobile, client.Email, client.DriverLicenceNo, client.BankDetails, client.SimNumber, client.NamePlateNumber, client.PhysicalAddress, client.OtherInfo);
            Assets.SaveChanges();

            var detials = Assets.Clients.Where(x => x.FirstName == client.FirstName && x.LastName == client.LastName && x.Mobile == client.Mobile).FirstOrDefault();

            client.ClientId = detials.ClientId;

            Assets.AddSubscription(client.ClientId, client.Terminal, client.StatusId, client.SubscriptionStartDate, client.RentAmount, client.PeriodTypeId, client.SubscriptionEndDate, client.Notes, client.EfposServiceCharge, client.ChitsCommission, client.LoanAmount, client.LoanDate);
            Assets.SaveChanges();

            return Json(true);

        }

        public ActionResult GetDriverDetails(int ClientId)
        {
            ReliableCabs.Models.ClientModel client = new ReliableCabs.Models.ClientModel();
            ViewBag.ClientId = ClientId;
            client.ClientId = ClientId;

            client.ListClients = Assets.Clients.Where(a => a.ClientId == ClientId).ToList();

            foreach (var item in client.ListClients)
            {
                client.ClientId = item.ClientId;
                client.FirstName = item.FirstName;
                client.LastName = item.LastName;
                client.Mobile = item.Mobile;
                client.Email = item.Email;
                client.DriverLicenceNo = item.DriverLicenceNo;
                client.BankDetails = item.BankDetails;
                client.SimNumber = item.SimNumber;
                client.NamePlateNumber = item.NamePlateNumber;
                client.PhysicalAddress = item.PhysicalAddress;
                client.OtherInfo = item.OtherInfo;
            }


            return View("GetDriverDetails", client);

        }

        [HttpPost]
        public ActionResult UpdateDriverDetails(Client client)
        {
            using (ReliablecabsEntities entities = new ReliablecabsEntities())
            {
                Client updatedClient = (from c in entities.Clients
                                        where c.ClientId == client.ClientId
                                        select c).FirstOrDefault();
                updatedClient.FirstName = client.FirstName;
                updatedClient.LastName = client.LastName;
                updatedClient.Email = client.Email;
                updatedClient.Mobile = client.Mobile;
                updatedClient.DriverLicenceNo = client.DriverLicenceNo;
                updatedClient.BankDetails = client.BankDetails;
                 updatedClient.SimNumber = client.SimNumber;
                 updatedClient.NamePlateNumber = client.NamePlateNumber;
                 updatedClient.PhysicalAddress = client.PhysicalAddress;
                 updatedClient.OtherInfo = client.OtherInfo;

                entities.SaveChanges();
            }

            return Json(true);
        }

       
        [HttpPost]
        public ActionResult DeleteDriverDetails(int ClientId)
        {
            using (ReliablecabsEntities entities = new ReliablecabsEntities())
            {
                Client client = (from c in entities.Clients
                                   where c.ClientId == ClientId
                                   select c).FirstOrDefault();
                entities.Clients.Remove(client);
                entities.SaveChanges();
            }

            //return new EmptyResult();
            return Json(true);
        }

       
    }
}

Views/Driver/Index.cshtml
@model IEnumerable<ReliableCabs.Models.ViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutHeader.cshtml";
}

<div class="container">
    <div class ="container .box .box-cell.box4" style="padding-left:30%">
        <table>
            <tr>
            <td>
                <h3 style="color:darkblue"><b>DRIVER DETAILS</b></h3>
            </td>
            <td style="padding-left:50%">
    <a href='../Driver/InsertDriverDetails' class="btn btn-info " style="padding-left:10%"> Add Driver Details</a> 

            </td>
             </tr>
        </table>
 </div>

   </div>

  <div class="row" style="padding-top:1%">

      <div class="col-sm-12" style=" padding-left:2%">
 <div class="white-box" >
  <table id="table_id" class="tablesaw table-striped table-hover table-bordered table">
    <thead>
        <tr style="background-color:#87CEEB">
            <th>Client Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Mobile</th>
             <th>Email</th>
             <th>Driver Licence No</th>
             <th>Bank Details </th>
             <th>Sim Number</th>
             <th>Name PlateNumber</th>
            <th >Terminal</th>
             <th >Status</th>
            <th ></th>
             <th  hidden></th>

   
        </tr>
    </thead>
    <tbody>
      
        @foreach (var item in Model)
        {
   
        <tr>
            <td>@item.client.ClientId</td>
            <td>@item.client.FirstName</td>
            <td>@item.client.LastName</td>
            <td>@item.client.Mobile</td>
            <td >@item.client.Email</td>
            <td>@item.client.DriverLicenceNo</td>
            <td>@item.client.BankDetails</td>
            <td>@item.client.SimNumber</td>
            <td>@item.client.NamePlateNumber</td>
             <td>@item.subscription.Terminal</td>
             <td>@item.status.Status1</td>
          
            <td style="width:100px">@*<button type="button" id="btnEdit" class="btnTrans" onclick="getdata(@item.ClientId)" >Edit</button>*@
              @*  <button type="button" id="btnDelete" class="btnTrans" onclick="deletedata(@item.ClientId)" >Delete</button>*@
                 <button class="btn_delete1" onclick="getdata(@item.client.ClientId)" title="Edit"><i class="fa fa-edit"></i></button>
                 <button class="btn_delete1" onclick="deletedata(@item.client.ClientId)" title="Delete"><i class="fa fa-trash"></i></button>
            </td>
            @* <td id="NetAmount" hidden>@Convert.ToDecimal(Model.ListFundsDetails.FirstOrDefault().NetAmount).ToString("0.00")</td>*@
             <td id="NetAmount" hidden>@ViewBag.NetAmount.ToString("0.00")</td>
          
             
             
        </tr>
           
    }
      
      
                 
        </tbody>
</table>
    
          </div>           

</div>

 </div>

@section scripts
{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   @* <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>*@
    <script src=" https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"></script>
    <script src="~/Content/plugins/components/datatables/jquery.dataTables.min.js"></script>
  
    <script>
        $(document).ready(function () {
            document.getElementById('Pendingamtnew').value = $("#NetAmount").text();
            //$("#ListAll").hide();
            datatabltInitialize();
        });

 

        function datatabltInitialize() {
            $('#table_id').DataTable({
                responsive: true,
                "oLanguage": {
                    "sSearch": "<b>Search :</b> "
                },


                columnDefs: [{
                    "width": "40px", "targets": [4],
                     "width": "40px", "targets": [5] 
                    //targets: [4, 5, 6, 7, 8, 9],
                    //render: $.fn.dataTable.render.number(',', '.', 2)
                }]
            });
            $('.dataTables_filter input[type="search"]').

  css({ 'width': '250px', 'height': '40px', 'background-color': '#e5ebec', 'align': 'right', 'display': 'inline-block', "position": "right", "left": "-100px" });

        }

    
     
        function getdata(ClientId) {
            var ClientId = ClientId;
            window.location.href = "@Url.Action("GetDriverDetails", "Driver")?ClientId=" + ClientId;

        }

        function deletedata(ClientId) {
            var ClientId = ClientId;
            //alert('Are you sure to delete row');
            @*   window.location.href = "@Url.Action("DeleteDriverDetails", "Driver")?ClientId=" + ClientId;*@
            $.ajax({
                type: "POST",
                url: "/Driver/DeleteDriverDetails",
                data: {
                    ClientId : ClientId

                },
                success: function (data) {
                    alert("Deleted Successfully");
                    window.location.href = "../Driver/Index"
                },

                error: function (jqXHR, status, text) {
                    alert("Not Submitted ");
                }

            });

        }

</script>
    }

Views/Driver/PartialDriverIndex.cshtml
@model ReliableCabs.Models.ClientModel

  <div class="row" style="padding-top:1%">
 <div class="col-sm-12" style=" padding-left:2%">
 <div class="white-box" >
  <table id="table_id" class="tablesaw table-striped table-hover table-bordered table">
    <thead>
        <tr style="background-color:#87CEEB">
            <th>Client Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Mobile</th>
             <th>Email</th>
             <th>Driver Licence No</th>
             <th>Bank Details </th>
             <th>Sim Number</th>
             <th>Name PlateNumber</th>
            
            <th ></th>
             <th  hidden></th>

   
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
    {
        foreach (var item in Model.ListClients)
            {
   
        <tr>
            <td>@item.ClientId</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Mobile</td>
            <td >@item.Email</td>
            <td>@item.DriverLicenceNo</td>
            <td>@item.BankDetails</td>
            <td>@item.SimNumber</td>
            <td>@item.NamePlateNumber</td>
          
            <td style="width:100px">@*<button type="button" id="btnEdit" class="btnTrans" onclick="getdata(@item.ClientId)" >Edit</button>*@
              @*  <button type="button" id="btnDelete" class="btnTrans" onclick="deletedata(@item.ClientId)" >Delete</button>*@
                 <button class="btn_delete1" onclick="getdata(@item.ClientId)" title="Edit"><i class="fa fa-edit"></i></button>
                 <button class="btn_delete1" onclick="deletedata(@item.ClientId)" title="Delete"><i class="fa fa-trash"></i></button>
            </td>
             <td id="NetAmount" hidden>@Convert.ToDecimal(Model.ListFundsDetails.FirstOrDefault().NetAmount).ToString("0.00")</td>
          
             
             
        </tr>
        }   
        }
      
      
                 
        </tbody>
</table>
    
          </div>           

</div>
      </div>